GET http://localhost:8080/user/thehippokid

###
GET http://localhost:8080/league/captaincarey/winner

###
GET http://localhost:8080/league/727997364425617408/bracket/WINNER

###
GET http://localhost:8080/league/727997364425617408/members

###
GET http://localhost:8080/user/thehippokid/players/most-used
